server:
  port: 8081

spring:
  application:
    name: rocketmq-example-consumer

#rocketmq配置
cloud:
  rocketmq:
    #不能使用name-server
    name-server: 139.196.208.53:9876
    producer:
      #生产者组名称
      group-name: p-${spring.application.name}
    consumer:
      #消费者组名称
      group-name: c-example-consumer
    #acl权限认证
    acl:
      accessKey: zhoushuai
      secretKey: zs19921119


logging:
  level:
    RocketmqClient: error
    RocketmqRemoting: warn
