server:
  port: 8080

spring:
  application:
    name: rocketmq-example-producer

#rocketmq配置
cloud:
  rocketmq:
    #不能使用name-server
    name-server: 139.196.208.53:9876
    producer:
      #生产者组名称
      group-name: p-${spring.application.name}

logging:
  level:
    RocketmqClient: error
    RocketmqRemoting: warn
