server:
  port: 8080

spring:
  application:
    name: rocketmq-example-producer

#rocketmq配置
cloud:
  rocketmq:
    #不能使用name-server
    name-server: 139.196.208.53:9876
    producer:
      #生产者组名称
      group-name: p-${spring.application.name}
    #acl权限认证
    acl:
      accessKey: zhoushuai
      secretKey: zs19921119

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

logging:
  level:
    RocketmqClient: error
    RocketmqRemoting: warn
