server:
  port: 8080

spring:
  application:
    name: rocketmq-example-producer

#rocketmq配置
cloud:
  rocketmq:
    #不能使用name-server
    nameServer: 139.196.208.53:9876
    producer:
      group: p-${spring.application.name}

logging:
  level:
    RocketmqClient: error
    RocketmqRemoting: warn